name: flutter_androssy
description: Collection of service with advanced style and controlling system.
version: 0.1.9-alpha4
homepage: https://github.com/P-YMR/flutter_androssy.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  badges: ^3.1.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  