name: flutter_androssy
description: Collection of service with advanced style and controlling system.
version: 1.0.0-alpha3
homepage: https://github.com/P-YMR/flutter_androssy.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:

  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_androssy_kits: ^1.0.1-alpha1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  